### ISSUE TITLE
Weak signal

### ISSUE THREAD

**Issue by josinaldobarbosa** [benb0jangles/FlySky-i6-Mod-#110]
in some mod of these has how to put the weak radio signal (error) to emit beeps?

**Comment by qba667** [comment]
@josinaldobarbosa sure we have custom alarms - depending on telemetry values. Try version 1.7.5.

**Comment by josinaldobarbosa** [comment]
@qba667 Where do I find this version?

**Comment by qba667** [comment]
@josinaldobarbosa 
https://github.com/qba667/FlySkyI6

**Comment by josinaldobarbosa** [comment]
@qba667 thank you!
