### ISSUE TITLE
fs-i6 bootloader

### ISSUE THREAD

**Issue by hanmaki** [benb0jangles/FlySky-i6-Mod-#129]
hello，because i mistake the  voltage， the fs-i6‘s mcu and 3.3v ic burned down，i  have changed it， i think i need the bootloader or the way to flash the firmware，is there any way to fix it？

**Comment by DeADLoCK-GUI** [comment]
> hello，because i mistake the  voltage， the fs-i6‘s mcu and 3.3v ic burned down，i  have changed it， i think i need the bootloader or the way to flash the firmware，is there any way to fix it？

did u find a solution so far i did the same thing but dont know how to flash the replaced chip
