### ISSUE TITLE
10 Channel Mod with FS-iA6B?

### ISSUE THREAD

**Issue by sebastianha** [benb0jangles/FlySky-i6-Mod-#20]
Hi,

first of all thank you very much for alle the mods!

I have one question regarding the 10 channel mod: Can I use alle the 10 channels with my FS-iA6B receiver in PPM mode? Or do I need a 10 channel receiver to make use of the extra channels?

Update: As far as I understand I can use 10 channels with this receiver by selecting IBus or I need a IBus to PPM converter and have 8 (or 10?) channels, is that correct?

**Comment by jarno83** [comment]
Hi, yes thats true. This is what I did, and it's working well :)

**Comment by sebastianha** [comment]
Thanks!
