### ISSUE TITLE
Bricked fs-i6

### ISSUE THREAD

**Issue by GioSci** [benb0jangles/FlySky-i6-Mod-#31]
After the flashing (100%) the transmitter doesn't restart itself and remain in update mode, I turned it off and now it doesn't came on. Anyone know what i have to do?

**Comment by lrusnac** [comment]
flash it again

**Comment by grizzle245** [comment]
rudder trim right throttle trim down. and turn on... screen will stay blank but you can flash

**Comment by GioSci** [comment]
Thanks I've solved

**Comment by GioSci** [comment]
I had to try many times because the tx didn't enter the update mode but finally it works
