### ISSUE TITLE
3-position SwB

### ISSUE THREAD

**Issue by Sh0tek61** [benb0jangles/FlySky-i6-Mod-#65]
FS-i6 hardware is ready to use 3-position switch instead of SwB - just one wire and 2 resistors needed, but firmware only detect two states of this switch - below 1.5V and above (checked with potentiometer between 3.3V and Gnd, firmware 10ch_Timer_MOD_i6_Programmer_V1_4). Is it possible to adapt fw, so it'll work exactly as SwC?

**Comment by qba667** [comment]
Sure, I have working code but I have to change all usages of SwB

**Comment by Sh0tek61** [comment]
Thanx a lot, I am looking forward to this feature
