### ISSUE TITLE
tx battery sound + bind bug

### ISSUE THREAD

**Issue by zelwake** [benb0jangles/FlySky-i6-Mod-#74]
Can I disable or adjust when will tx beep? Right now when tx battery drops by 0.01V there is a beep which is higly annoying. Might be fixed in newest qba667 version, havent tried yet.

Binding. That thing is pretty bad atm. Had to turn on in second menu, hit Bind, held bind button on rx, plugged battery, tx showed "binding ok" but couldn't arm. Had to turn off and on tx and hit Bind again (no turning on/off quad) and it finally took signal. Was scratching my head for 10 minutes before I figured this out.

**Comment by qba667** [comment]
@zelwake I am trying to figure out what is causing this issue. Can you give me a hint? What was last working version?

**Comment by zelwake** [comment]
this is the first version (here) of yours project i use, before I was using 10ch timer...actually it is working, kinda harder to bind (more steps), but its working
wonderful, setting tx alarm got rid of the annoying reminder beep, thanks for that tip

**Comment by qba667** [comment]
@zelwake 10ch timer was also mine - so it was working before. I have to verify all changes.

**Comment by zelwake** [comment]
@qba667 really? thats nice!....anyway, managed to test ia6b receiver and didnt need to rebind, it can also be just x6b receiver issue

**Comment by qba667** [comment]
@zelwake 
Binding issue resolved can you try:
https://www.rcgroups.com/forums/showthread.php?2486545-FlySky-FS-i6-8-channels-firmware-patch%21/page128

**Comment by zelwake** [comment]
@qba667 
alright, bind button works nicely now, rebinded (rebound?) both ia6b and x6b at first try, gonna try later with afhds receiver on my micro

**Comment by zelwake** [comment]
okay, working with AFHDS too, I think problems are solved
