### ISSUE TITLE
all  this firmaware for i6 is useless

### ISSUE THREAD

**Issue by Juli79** [benb0jangles/FlySky-i6-Mod-#75]
for me and others which  have a naza flight controller ...is useless without the endpoints for all channels

**Comment by Gryd3** [comment]
Juli79, then the solution for you, and others like you is pretty obvious.
Don't use it. The mod works amazingly well for flight controllers that support serial TX, and I can certainly claim that the function I gain with the mod is well worth the effort and mod when used with a serial TX capable FC and firmware (Naze32 and Skyline32 personally).

**Comment by qba667** [comment]
@Juli79 there is already source code published to handle channels 7-10. Just waiting for some willing to invest time and rework the method. EEPROM access is also provided. Instead of complaining start working and provide something to the community.

**Comment by alandroid** [comment]
@Juli79 "Useless for Naza". For everyone else, much useful, this software is #yoda
